# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 179614f240f0a0ce4baaada6a5ab4e9df264bdd690107e2ba4699ac7d6d7c60216c371c3c3f7cc4caa4a3a08205bc185dc126212c357b397ec0cee1307d6651b

test:
  secret_key_base: e197785d38174e38a24108524878ea1e38b1bccd4ea86ebe88011c60203c43662ec17be9058de1f8747d4027b1862630519523ac4a71ea5b29f765e5dfd9fda4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
